export const data = {
  about: "ph:info-duotone",
  recentPosts: "ph:newspaper-duotone",
  projects: "ph:acorn-duotone",
  techStack: "ph:code-duotone",
  friends: "ph:users-duotone",
  words: "ph:align-left-bold",
  time: "ph:timer-bold",
  link: "ph:link-bold",
  calendar: "ph:calendar-blank-duotone",
  category: "ph:book-bookmark-duotone",
  tag: "ph:tag-duotone",
  new: "ph:folder-duotone",
  open: "ph:link-duotone",
  edit: "ph:pen-duotone",
  delete: "ph:trash-duotone",
  moment: "ph:clock-duotone",
  github: "ph:github-logo-duotone",
  location: "ph:bank-duotone",
  heart: "ph:heartbeat-duotone",
};
